[workspace]
channels = ["conda-forge"]
name = "nn-pytorch"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
pip = ">=25.2,<26"
black = ">=25.1.0,<26"

[pypi-dependencies]
pandas = ">=2.3.2, <3"
numpy = ">=2.3.3, <3"
matplotlib = ">=3.10.6, <4"
jupyter = ">=1.1.1, <2"
seaborn = ">=0.13.2, <0.14"
